//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZZ_LIST_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ZZ_LIST_INFO()
        {
            this.T_ZZ_MOULD_INFO = new HashSet<T_ZZ_MOULD_INFO>();
        }
    
        public string ID { get; set; }
        public string MOULD_NUMBER { get; set; }
        public string DEPT_ID { get; set; }
        public string HY_CODE { get; set; }
        public string ZZ_NAME { get; set; }
        public string YW_NAME { get; set; }
        public string IS_PROVINCE { get; set; }
        public string IS_CITY { get; set; }
        public string IS_COUNTY { get; set; }
        public string REMARKS { get; set; }
        public string HAVE_SON_METADATA { get; set; }
        public string USER_ID { get; set; }
        public string CZ_STATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ZZ_MOULD_INFO> T_ZZ_MOULD_INFO { get; set; }
    }
}
