//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZZ_ZM_INFO
    {
        public string ID { get; set; }
        public string MOULD_ID { get; set; }
        public string DZZZ_NO { get; set; }
        public string ZZ_BH { get; set; }
        public Nullable<System.DateTime> BZ_DATE { get; set; }
        public Nullable<System.DateTime> STAR_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string DEPT_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string USER_TYPE { get; set; }
        public string USER_ZJ_TYPE { get; set; }
        public string USER_N0 { get; set; }
        public string ZZ_TYPE { get; set; }
        public string INDIVIDUATION { get; set; }
        public byte[] ZZ_FILE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string STATE { get; set; }
        public string STATUS { get; set; }
    }
}
