//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ZZ_METADATA_INFO
    {
        public string ID { get; set; }
        public string MOULD_ID { get; set; }
        public string PARENT_ID { get; set; }
        public string COLUMN_NAME { get; set; }
        public string COLUMN_TYPE { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
