//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.ZZSF_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.zs.com/", ConfigurationName="ZZSF_WS.publicpayService")]
    public interface publicpayService {
        
        // CODEGEN: 命名空间 http://server.zs.com/ 的元素名称 slbh 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Web4BDC.ZZSF_WS.GetPayInfoResponse GetPayInfo(Web4BDC.ZZSF_WS.GetPayInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayInfo", Namespace="http://server.zs.com/", Order=0)]
        public Web4BDC.ZZSF_WS.GetPayInfoBody Body;
        
        public GetPayInfo() {
        }
        
        public GetPayInfo(Web4BDC.ZZSF_WS.GetPayInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://server.zs.com/")]
    public partial class GetPayInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string slbh;
        
        public GetPayInfoBody() {
        }
        
        public GetPayInfoBody(string slbh) {
            this.slbh = slbh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPayInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPayInfoResponse", Namespace="http://server.zs.com/", Order=0)]
        public Web4BDC.ZZSF_WS.GetPayInfoResponseBody Body;
        
        public GetPayInfoResponse() {
        }
        
        public GetPayInfoResponse(Web4BDC.ZZSF_WS.GetPayInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetPayInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetPayInfoResponseBody() {
        }
        
        public GetPayInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface publicpayServiceChannel : Web4BDC.ZZSF_WS.publicpayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class publicpayServiceClient : System.ServiceModel.ClientBase<Web4BDC.ZZSF_WS.publicpayService>, Web4BDC.ZZSF_WS.publicpayService {
        
        public publicpayServiceClient() {
        }
        
        public publicpayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public publicpayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public publicpayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public publicpayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web4BDC.ZZSF_WS.GetPayInfoResponse Web4BDC.ZZSF_WS.publicpayService.GetPayInfo(Web4BDC.ZZSF_WS.GetPayInfo request) {
            return base.Channel.GetPayInfo(request);
        }
        
        public string GetPayInfo(string slbh) {
            Web4BDC.ZZSF_WS.GetPayInfo inValue = new Web4BDC.ZZSF_WS.GetPayInfo();
            inValue.Body = new Web4BDC.ZZSF_WS.GetPayInfoBody();
            inValue.Body.slbh = slbh;
            Web4BDC.ZZSF_WS.GetPayInfoResponse retVal = ((Web4BDC.ZZSF_WS.publicpayService)(this)).GetPayInfo(inValue);
            return retVal.Body.@return;
        }
    }
}
