//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.TaxService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/zhuanfa_qsxx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string zhuanfa_qsxx(string txm, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/zhuanfa_jtcy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Web4BDC.TaxService.CProofVo zhuanfa_jtcy(string proofcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHouseQs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getHouseQs(string txm, string uid, string dist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getJTCY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Web4BDC.TaxService.CProofVo getJTCY(string proofcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/csdzbah", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string csdzbah(string dzbah, string fzrq, string ly);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TaxWSBiz")]
    public partial class CProofVo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string 申请编号Field;
        
        private string 利用单位Field;
        
        private string 经办日期Field;
        
        private string 申请人Field;
        
        private string 申请人证件类型Field;
        
        private string 申请人证件号码Field;
        
        private CProofPerson[] proofpersonListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string 申请编号 {
            get {
                return this.申请编号Field;
            }
            set {
                this.申请编号Field = value;
                this.RaisePropertyChanged("申请编号");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string 利用单位 {
            get {
                return this.利用单位Field;
            }
            set {
                this.利用单位Field = value;
                this.RaisePropertyChanged("利用单位");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string 经办日期 {
            get {
                return this.经办日期Field;
            }
            set {
                this.经办日期Field = value;
                this.RaisePropertyChanged("经办日期");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string 申请人 {
            get {
                return this.申请人Field;
            }
            set {
                this.申请人Field = value;
                this.RaisePropertyChanged("申请人");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string 申请人证件类型 {
            get {
                return this.申请人证件类型Field;
            }
            set {
                this.申请人证件类型Field = value;
                this.RaisePropertyChanged("申请人证件类型");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string 申请人证件号码 {
            get {
                return this.申请人证件号码Field;
            }
            set {
                this.申请人证件号码Field = value;
                this.RaisePropertyChanged("申请人证件号码");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public CProofPerson[] proofpersonList {
            get {
                return this.proofpersonListField;
            }
            set {
                this.proofpersonListField = value;
                this.RaisePropertyChanged("proofpersonList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="TaxWSBiz")]
    public partial class CProofPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string 姓名Field;
        
        private string 证件类型Field;
        
        private string 证件号码Field;
        
        private string 房屋座落Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string 姓名 {
            get {
                return this.姓名Field;
            }
            set {
                this.姓名Field = value;
                this.RaisePropertyChanged("姓名");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string 证件类型 {
            get {
                return this.证件类型Field;
            }
            set {
                this.证件类型Field = value;
                this.RaisePropertyChanged("证件类型");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string 证件号码 {
            get {
                return this.证件号码Field;
            }
            set {
                this.证件号码Field = value;
                this.RaisePropertyChanged("证件号码");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string 房屋座落 {
            get {
                return this.房屋座落Field;
            }
            set {
                this.房屋座落Field = value;
                this.RaisePropertyChanged("房屋座落");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Web4BDC.TaxService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Web4BDC.TaxService.ServiceSoap>, Web4BDC.TaxService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string zhuanfa_qsxx(string txm, string uid) {
            return base.Channel.zhuanfa_qsxx(txm, uid);
        }
        
        public Web4BDC.TaxService.CProofVo zhuanfa_jtcy(string proofcode) {
            return base.Channel.zhuanfa_jtcy(proofcode);
        }
        
        public string getHouseQs(string txm, string uid, string dist) {
            return base.Channel.getHouseQs(txm, uid, dist);
        }
        
        public Web4BDC.TaxService.CProofVo getJTCY(string proofcode) {
            return base.Channel.getJTCY(proofcode);
        }
        
        public string csdzbah(string dzbah, string fzrq, string ly) {
            return base.Channel.csdzbah(dzbah, fzrq, ly);
        }
    }
}
