//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenTest.ZZDY_WS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZZDY_WS.ZZDZ_SUININGSoap")]
    public interface ZZDZ_SUININGSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LND_PROC_GETCERTQUERY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LND_PROC_GETCERTQUERY(string LZRZJH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LND_PROC_GETCERTINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LND_PROC_GETCERTINFO(string ywh, string QLRZJH, string BDCQZH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LND_PROC_UPDATECERTINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int LND_PROC_UPDATECERTINFO(string YWH, string QLRZJH, string BDCQZH, string LZRXM, string LZRZJH, string YSXLH, string YSXLHP, string machineCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LND_PROC_UPDATECOST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int LND_PROC_UPDATECOST(string YWH, string QLRZJH, string BDCQZH, float cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LND_PROC_UPDATECERTSTATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int LND_PROC_UPDATECERTSTATE(string YWH, string QLRZJH, string BDCQZH, int state, string machineCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZZDZ_SUININGSoapChannel : SevenTest.ZZDY_WS.ZZDZ_SUININGSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZZDZ_SUININGSoapClient : System.ServiceModel.ClientBase<SevenTest.ZZDY_WS.ZZDZ_SUININGSoap>, SevenTest.ZZDY_WS.ZZDZ_SUININGSoap {
        
        public ZZDZ_SUININGSoapClient() {
        }
        
        public ZZDZ_SUININGSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZZDZ_SUININGSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZZDZ_SUININGSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZZDZ_SUININGSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable LND_PROC_GETCERTQUERY(string LZRZJH) {
            return base.Channel.LND_PROC_GETCERTQUERY(LZRZJH);
        }
        
        public System.Data.DataTable LND_PROC_GETCERTINFO(string ywh, string QLRZJH, string BDCQZH) {
            return base.Channel.LND_PROC_GETCERTINFO(ywh, QLRZJH, BDCQZH);
        }
        
        public int LND_PROC_UPDATECERTINFO(string YWH, string QLRZJH, string BDCQZH, string LZRXM, string LZRZJH, string YSXLH, string YSXLHP, string machineCode) {
            return base.Channel.LND_PROC_UPDATECERTINFO(YWH, QLRZJH, BDCQZH, LZRXM, LZRZJH, YSXLH, YSXLHP, machineCode);
        }
        
        public int LND_PROC_UPDATECOST(string YWH, string QLRZJH, string BDCQZH, float cost) {
            return base.Channel.LND_PROC_UPDATECOST(YWH, QLRZJH, BDCQZH, cost);
        }
        
        public int LND_PROC_UPDATECERTSTATE(string YWH, string QLRZJH, string BDCQZH, int state, string machineCode) {
            return base.Channel.LND_PROC_UPDATECERTSTATE(YWH, QLRZJH, BDCQZH, state, machineCode);
        }
    }
}
