//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCWebServices.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.BDCSrvSoap")]
    public interface BDCSrvSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="/FC_H", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FCWebServices.ServiceReference1.BDC FC_H(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/FC_Z", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FCWebServices.ServiceReference1.BDC FC_Z(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/CLF_FC_CLMMHT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FCWebServices.ServiceReference1.BDC CLF_FC_CLMMHT(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/FC_GFQLRXX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FCWebServices.ServiceReference1.BDC FC_GFQLRXX(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/FC_SPFYGHT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FCWebServices.ServiceReference1.BDC FC_SPFYGHT(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/SPF_FC_CLMMHT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FCWebServices.ServiceReference1.BDC SPF_FC_CLMMHT(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateSealStateForSPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateSealStateForSPF(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateMortgageStateForSPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateMortgageStateForSPF(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateYGDJStateForSPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateYGDJStateForSPF(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateCSDJStateForSPF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateCSDJStateForSPF(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/SPF_WFZMCX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SPF_WFZMCX(string qlrxm, string zjhm, string zl);
        
        [System.ServiceModel.OperationContractAttribute(Action="/SPF_FC_FWQK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SPF_FC_FWQK(string sParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateSealStateForCG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateSealStateForCG(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateMortgageStateForCG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateMortgageStateForCG(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateYGDJStateForCG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateYGDJStateForCG(System.Data.DataSet dsHouses, string Area);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UpdateCSDJStateForCG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UpdateCSDJStateForCG(System.Data.DataSet dsHouses, string Area);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BDC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Head headField;
        
        private System.Data.DataSet dataField;
        
        private System.Data.DataSet attachField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Head head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
                this.RaisePropertyChanged("head");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Data.DataSet data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet attach {
            get {
                return this.attachField;
            }
            set {
                this.attachField = value;
                this.RaisePropertyChanged("attach");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Head : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int flagField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BDCSrvSoapChannel : FCWebServices.ServiceReference1.BDCSrvSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDCSrvSoapClient : System.ServiceModel.ClientBase<FCWebServices.ServiceReference1.BDCSrvSoap>, FCWebServices.ServiceReference1.BDCSrvSoap {
        
        public BDCSrvSoapClient() {
        }
        
        public BDCSrvSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDCSrvSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDCSrvSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDCSrvSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public FCWebServices.ServiceReference1.BDC FC_H(string sParams) {
            return base.Channel.FC_H(sParams);
        }
        
        public FCWebServices.ServiceReference1.BDC FC_Z(string sParams) {
            return base.Channel.FC_Z(sParams);
        }
        
        public FCWebServices.ServiceReference1.BDC CLF_FC_CLMMHT(string sParams) {
            return base.Channel.CLF_FC_CLMMHT(sParams);
        }
        
        public FCWebServices.ServiceReference1.BDC FC_GFQLRXX(string sParams) {
            return base.Channel.FC_GFQLRXX(sParams);
        }
        
        public FCWebServices.ServiceReference1.BDC FC_SPFYGHT(string sParams) {
            return base.Channel.FC_SPFYGHT(sParams);
        }
        
        public FCWebServices.ServiceReference1.BDC SPF_FC_CLMMHT(string sParams) {
            return base.Channel.SPF_FC_CLMMHT(sParams);
        }
        
        public System.Data.DataSet UpdateSealStateForSPF(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateSealStateForSPF(dsHouses, Area);
        }
        
        public System.Data.DataSet UpdateMortgageStateForSPF(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateMortgageStateForSPF(dsHouses, Area);
        }
        
        public System.Data.DataSet UpdateYGDJStateForSPF(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateYGDJStateForSPF(dsHouses, Area);
        }
        
        public System.Data.DataSet UpdateCSDJStateForSPF(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateCSDJStateForSPF(dsHouses, Area);
        }
        
        public System.Data.DataSet SPF_WFZMCX(string qlrxm, string zjhm, string zl) {
            return base.Channel.SPF_WFZMCX(qlrxm, zjhm, zl);
        }
        
        public System.Data.DataSet SPF_FC_FWQK(string sParams) {
            return base.Channel.SPF_FC_FWQK(sParams);
        }
        
        public System.Data.DataSet UpdateSealStateForCG(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateSealStateForCG(dsHouses, Area);
        }
        
        public System.Data.DataSet UpdateMortgageStateForCG(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateMortgageStateForCG(dsHouses, Area);
        }
        
        public System.Data.DataSet UpdateYGDJStateForCG(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateYGDJStateForCG(dsHouses, Area);
        }
        
        public System.Data.DataSet UpdateCSDJStateForCG(System.Data.DataSet dsHouses, string Area) {
            return base.Channel.UpdateCSDJStateForCG(dsHouses, Area);
        }
    }
}
