//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCForFCWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DJ_FJD_LJR
    {
        public string LJBH { get; set; }
        public string SLBH { get; set; }
        public string LJR { get; set; }
        public string LJRSFZJLX { get; set; }
        public string LJRSFZJH { get; set; }
        public string LJRYQLRDGX { get; set; }
        public byte[] LJRZW { get; set; }
        public byte[] LJRZP { get; set; }
        public byte[] ZWTZM { get; set; }
        public Nullable<decimal> TRANSNUM { get; set; }
    }
}
