//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models.BDCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DJ_QLRGL
    {
        public string GLBM { get; set; }
        public string SLBH { get; set; }
        public string YWBM { get; set; }
        public string QLRID { get; set; }
        public string GYFS { get; set; }
        public string GYFE { get; set; }
        public string CZFS { get; set; }
        public string CZBH { get; set; }
        public string BDCZH { get; set; }
        public string ZSXLH { get; set; }
        public Nullable<decimal> SXH { get; set; }
        public string QLRLX { get; set; }
        public string QLRMC { get; set; }
        public string GX { get; set; }
        public Nullable<decimal> LIFECYCLE { get; set; }
        public Nullable<short> TRANSNUM { get; set; }
        public string ZJHM { get; set; }
        public string ZJLB { get; set; }
        public string IMPORTNAME { get; set; }
        public string DZZSXLH { get; set; }
        public string DH { get; set; }
        public string TMP_PLHB_QLRID { get; set; }
        public Nullable<System.DateTime> TRANSNUM2 { get; set; }
    }
}
