//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models.BDCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DJ_SJD
    {
        public string SLBH { get; set; }
        public string DJDL { get; set; }
        public string DJXL { get; set; }
        public string LCLX { get; set; }
        public string LCBM { get; set; }
        public string LCMC { get; set; }
        public string ZL { get; set; }
        public string SJR { get; set; }
        public Nullable<System.DateTime> SJSJ { get; set; }
        public Nullable<System.DateTime> CNSJ { get; set; }
        public string QXDM { get; set; }
        public string TZRXM { get; set; }
        public string TZFS { get; set; }
        public string TZRDH { get; set; }
        public string TZRYDDH { get; set; }
        public string TZRDZYJ { get; set; }
        public string TZRTXDZ { get; set; }
        public string CXMM { get; set; }
        public string SJMC { get; set; }
        public string SJLX { get; set; }
        public Nullable<decimal> SJSL { get; set; }
        public Nullable<decimal> YS { get; set; }
        public string SFSYBZ { get; set; }
        public string SFEWSJ { get; set; }
        public string SFBCSJ { get; set; }
        public string ZRKS { get; set; }
        public string ZRR { get; set; }
        public string YXJ { get; set; }
        public string SJBZ { get; set; }
        public string BCSM { get; set; }
        public string FCSLH { get; set; }
        public string FCDJLX { get; set; }
        public string FCHID { get; set; }
        public string BIZMSGID { get; set; }
        public string JRYWBM { get; set; }
        public Nullable<decimal> SBZT { get; set; }
        public Nullable<decimal> SBXZCS { get; set; }
        public string CERTINUM { get; set; }
        public string CERTIINFO { get; set; }
        public Nullable<decimal> SBSTZT { get; set; }
        public string HTBH { get; set; }
        public Nullable<decimal> JHZT { get; set; }
        public string JYBH { get; set; }
        public string PCH { get; set; }
        public string AJZT { get; set; }
        public byte[] XCZP { get; set; }
        public string PRJID { get; set; }
        public string SHAREKEY { get; set; }
        public Nullable<System.DateTime> SHARETIME { get; set; }
        public string SHARESTATE { get; set; }
        public Nullable<decimal> TRANSNUM { get; set; }
        public string CGZT { get; set; }
        public string WWSQBH { get; set; }
        public string WWYYBH { get; set; }
        public string IMPORTNAME { get; set; }
        public string QYXS { get; set; }
        public string QXKZ { get; set; }
        public string GG_XMBH { get; set; }
        public Nullable<decimal> SBCS { get; set; }
        public Nullable<System.DateTime> SBSJ { get; set; }
        public string SBJG { get; set; }
        public Nullable<System.DateTime> TRANSNUM2 { get; set; }
    }
}
