//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models.BDCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DJ_XGDJGL
    {
        public string BGBM { get; set; }
        public string ZSLBH { get; set; }
        public string FSLBH { get; set; }
        public Nullable<System.DateTime> BGRQ { get; set; }
        public string BGLX { get; set; }
        public string XGZH { get; set; }
        public string XGZLX { get; set; }
        public string PID { get; set; }
        public Nullable<short> TRANSNUM { get; set; }
        public string IMPORTNAME { get; set; }
        public string MARK { get; set; }
        public string YULIU1 { get; set; }
        public Nullable<System.DateTime> TRANSNUM2 { get; set; }
    }
}
