//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4BDC.Models.BDCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FC_Z_QSDC
    {
        public string TSTYBM { get; set; }
        public Nullable<decimal> BSM { get; set; }
        public string ZDTYBM { get; set; }
        public string ZH { get; set; }
        public string LJZH { get; set; }
        public string FWBH { get; set; }
        public string BDCDYH { get; set; }
        public string XMMC { get; set; }
        public string JZWMC { get; set; }
        public Nullable<decimal> ZTS { get; set; }
        public string LPLB { get; set; }
        public string LZXZ { get; set; }
        public string LZTD { get; set; }
        public string FWZL { get; set; }
        public Nullable<decimal> QLRZS { get; set; }
        public string GHYT { get; set; }
        public string FWJG { get; set; }
        public Nullable<decimal> ZCS { get; set; }
        public Nullable<decimal> YCJZMJ { get; set; }
        public Nullable<decimal> SCJZMJ { get; set; }
        public Nullable<decimal> ZZDMJ { get; set; }
        public Nullable<decimal> ZYDMJ { get; set; }
        public Nullable<decimal> JZWGD { get; set; }
        public Nullable<System.DateTime> JGRQ { get; set; }
        public Nullable<decimal> DSCS { get; set; }
        public Nullable<decimal> DXCS { get; set; }
        public Nullable<decimal> DXSD { get; set; }
        public string BZ { get; set; }
        public string DCZ { get; set; }
        public Nullable<System.DateTime> DCSJ { get; set; }
        public string DCYJ { get; set; }
        public string FJSM { get; set; }
        public string WZBS { get; set; }
        public string WZSM { get; set; }
        public string ZMC { get; set; }
        public string MPH { get; set; }
        public Nullable<decimal> FCZRZBH { get; set; }
        public string OLDFWBH { get; set; }
        public string JCNF { get; set; }
        public string SHARESTATE { get; set; }
        public string BGJZXX { get; set; }
        public string BGTSXX { get; set; }
        public byte[] ZDT { get; set; }
        public byte[] ZDCT { get; set; }
        public string ISRGHS { get; set; }
        public string RGHSRY { get; set; }
        public Nullable<System.DateTime> RGHSRQ { get; set; }
        public Nullable<decimal> LIFECYCLE { get; set; }
        public Nullable<short> TRANSNUM { get; set; }
        public string ITEM { get; set; }
        public string YBZDH { get; set; }
        public string SZD { get; set; }
        public string SZN { get; set; }
        public string SZX { get; set; }
        public string SZB { get; set; }
        public string IMPORTNAME { get; set; }
        public string FWBH_OLD { get; set; }
        public string LPBH { get; set; }
        public Nullable<System.DateTime> SHARETIME { get; set; }
        public string XMBH { get; set; }
    }
}
